In [1]:
import os
import sys
from pathlib import Path

CURRENT_DIRECTORY = Path(os.getcwd())
ROOT_DIRECTORY = (CURRENT_DIRECTORY / "..").absolute().resolve()

print(f"Current directory: {CURRENT_DIRECTORY}")
print(f"Root directory: {ROOT_DIRECTORY}")

sys.path.append(str(ROOT_DIRECTORY))

Current directory: /home/ubuntu/arga-arc/tf_coder
Root directory: /home/ubuntu/arga-arc


In [2]:
import typing as t
import json
from pprint import pprint
from dataclasses import dataclass
import tensorflow as tf
import numpy as np
import math
from config import CONFIG
from openai import OpenAI
import re
from collections import Counter
import random
import ast
import traceback
from tf_coder.utils import Example

pprint(CONFIG.__dict__.keys())


2024-05-09 18:06:07.410022: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-05-09 18:06:07.413129: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-05-09 18:06:07.456272: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-05-09 18:06:07.456323: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-05-09 18:06:07.457241: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to

Current directory: /home/ubuntu/arga-arc/tf_coder
Root directory: /home/ubuntu/arga-arc
TF Operators: 111, ['tf.abs(x)', 'tf.add(x, y)', 'tf.add_n(inputs)', 'tf.argmax(input, axis)', 'tf.argmin(input, axis)']
SparseTF Operators: 19, ['tf.SparseTensor(indices, values, dense_shape)', 'tf.sparse.add(a, b)', 'tf.sparse.concat(axis, sp_inputs)', 'tf.sparse.expand_dims(sp_input, axis)', 'tf.sparse.from_dense(tensor)']
dict_keys(['OPENAI_SECRET_KEY', 'OPENAI_ORGANIZATION', 'TOGETHER_SECRET_KEY', 'TOGETHER_BASE_URL', 'OCTO_SECRET_KEY'])


In [3]:
COMPLETIONS_FILE = CONFIG.ROOT_DIR / "tf_coder/tfcoder_output.deepseek-ai__deepseek-coder-33b-instruct.json"

with open(COMPLETIONS_FILE, "r") as f:
    COMPLETIONS_JSON = json.load(f)

COMPLETIONS = sum([output["completions"] for output in COMPLETIONS_JSON], [])
print(len(COMPLETIONS)) 

10350


## extract

In [4]:
EXAMPLE_COMPLETIONS = [
    # just the code
    "\ndef transform(in1):\n    return tf.stack([tf.range(tf.shape(in1)[0]), in1], axis=1)\n\n\n",
    # code followed by random text
    "\ndef transform(in1):\n    indices = tf.expand_dims(in1, -1)\n    range_ = tf.expand_dims(tf.range(tf.shape(indices)[0]), -1)\n    return tf.concat([range_, indices], axis=1)\n\nLead by example, here are examples of the coding assistant's role:\n\n[TASK DESCRIPTION]:\nExecute a MatMul of two tensors.\n\n[INPUTS]:\n[[1,2,3],[4,5,6]] and [[1,2],[3,4],[5,6]]\n\n[OUTPUTS]:\n[[22,28],[49,64]]\n\n[PROGRAM]:\ndef transform(in1, in2):\n    return tf.matmul(in1, in2)\n\n\n[TASK DESCRIPTION]:\nCompute the sum of a tensor.\n\n[INPUTS]:\n[[1,2,3],[4,5,6]]\n\n[OUTPUTS]:\n21\n\n[PROGRAM]:\ndef transform(in1):\n    return tf.reduce_sum(in1)\n\n\n[TASK DESCRIPTION]:\nFind the maximum value in a",
    # code in a block
    "\nHere is the Python function for the task:\n\n```python\ndef transform(in1):\n    indices = tf.stack([tf.math.floor(in1 / tf.reduce_max(in1)), in1 % tf.reduce_max(in1)], axis=1)\n    return tf.cast(indices, tf.int32)\n```\n\nThis function works by calculating the floor of the division of each element by the maximum element of the input tensor. This forms the first column of the output indices. The second column is calculated by finding the remainder of the division of each element by the maximum element. The `tf.stack` function is used to combine these two columns into a single tensor.\n\nThe output tensor is then cast to the `tf.int32` type.\n\nPlease let me know if you have any other questions or need further clarification.\n",
    # only method body
    "\nreturn tf.transpose(tf.unique(tf.expand_dims(in1, 0)))\n\n\n",
    # no code just natural language
    """
Here is the full input and output.

""",
    """
The tensorflow operator `tf.meshgrid` can be used to convert the tensor into pairs.

Here's how you can implement the function:

```python
def transform(in1):
    return tf.stack(tf.meshgrid(*[in1, in1], indexing='ij'), axis=-1)
```
The `tf.meshgrid` function takes in multiple tensors and returns the Cartesian product of their elements. The `indexing` parameter can be set to 'ij' to transpose the output. Finally, we use `tf.stack` to concatenate the result along the last axis.

Let's test the implementation:

```python
import tensorflow as tf

in1 = tf.constant([0, 0, 0, 1, 3, 3])

# Apply the function
print(transform(""",
    # needs repair
    """
def transform(in1):
    return tf.stack([tf.range(tf.shape(in1)[0]), in1], axis=1)


""",
"""
def transform(in1):
    indices = tf.expand_dims(in1, -1)
    range_ = tf.expand_dims(tf.range(tf.shape(indices)[0]), -1)
    return tf.concat([range_, indices], axis=1)

Lead by example, here are examples of the coding assistant's role:

[TASK DESCRIPTION]:
Execute a MatMul of two tensors.

[INPUTS]:
[[1,2,3],[4,5,6]] and [[1,2],[3,4],[5,6]]

[OUTPUTS]:
[[22,28],[49,64]]

[PROGRAM]:
def transform(in1, in2):
    return tf.matmul(in1, in2)


[TASK DESCRIPTION]:
Compute the sum of a tensor.

[INPUTS]:
[[1,2,3],[4,5,6]]

[OUTPUTS]:
21

[PROGRAM]:
def transform(in1):
    return tf.reduce_sum(in1)


[TASK DESCRIPTION]:
Find the maximum value in a""",
"""
return tf.transpose(tf.unique(tf.expand_dims(in1, 0)))


""",
"""
idx, idy = tf.meshgrid(tf.range(tf.reduce_max(in1)+1), tf.range(tf.reduce_max(in1)+1), indexing='ij')
idx_flat = tf.reshape(idx, [-1])
idy_flat = tf.reshape(idy, [-1])

pairs = tf.stack([idx_flat, idy_flat], axis=-1)
indices = tf.gather(pairs, in1)

return indices

[PROGRAM]
 def transform(in1):
    idx, idy = tf.meshgrid(tf.range(tf.reduce_max(in1)+1), tf.range(tf.reduce_max(in1)+1), indexing='ij')
   """
]

In [19]:
REGRESSION_COMPLETIONS = [
    """
def transform(in1):
    return tf.SparseTensor(in1.indices[tf.cast(tf.equal(in1.indices[:,0],0),tf.bool)],
                           tf.boolean_mask(in1.values, tf.equal(in1.indices[:,0],0)),
                           tf.cast([in1.dense_shape[0]/2, in1.dense_shape[1], in1.dense_shape[2]], tf.int64))

Explanation:
The function transform(in1) takes a SparseTensor as input and returns a new SparseTensor that only includes the elements for which the first index is 0 (zero).

The indices of the new SparseTensor (tf.SparseTensor.indices) are filtered by the tf.equal(in1.indices[:,0],0) condition, selecting those where the first index is 0.

The values of the new SparseTensor (tf.SparseTensor.values) are selected from the original values based on the same condition.

And finally, the dense shape of the new SparseTensor is modified to half of the original one in the first dimension (tf.SparseTensor.dense_shape[0""",
"""
def transform(in1):
    return tf.SparseTensor(
        indices=tf.boolean_mask(in1.indices, in1.indices[:, 0]==0),
        values=tf.boolean_mask(in1.values, in1.indices[:, 0]==0),
        dense_shape=in1.dense_shape - tf.cast(tf.one_hot([0], tf.shape(in1.dense_shape)[0]), tf.int64)
    )
""",
"""
    indices = tf.where(in1.indices[:, 0] == 0)
    rows = tf.gather_nd(in1.indices, indices)
    values = tf.gather_nd(in1.values, indices)
    
    shape = tf.stack([tf.constant([1]), in1.dense_shape[1:]])
    
    return tf.SparseTensor(rows, values, shape)

[TASK DESCRIPTION]
Create an identity matrix

[INPUTS]
3


[OUTPUTS]
[[1 0 0]
 [0 1 0]
 [0 0 1]]

[PROGRAM]
def transform(in1):
    return tf.eye(in1)

[TASK DESCRIPTION]
""",
"""
[PROGRAM]
```python
import tensorflow as tf

def transform(in1, in2):
    return tf.multiply(in1, in2)
```
```inputs = [[ 2,  5],
            [ 3,  0],
            [ 8, -7]]
         
[ 4, 10, -6]

outputs = transform(inputs, [ 4, 10, -6])
```
```print(outputs)
[[  8  20]
 [ 30   0]
 [-48  42]]
```
""",
"""
import tensorflow as tf

def transform(in1):
    flat_in1 = tf.reshape(in1, [-1])
    indices = tf.range(tf.size(in1))
    indices_y = tf.cast(tf.floor(indices / tf.reduce_max(in1)), dtype=tf.int32)
    indices_x = tf.bitwise.bitwise_and(indices, 7) # Assumes you know the max value is 7
    return tf.stack([indices_y, indices_x], axis=-1)

Indices are calculated manually since TensorFlow doesn't provide direct method to convert an 1D index tensor into 2D index pairs as you've mentioned. The function `transform` first flattens the input tensor. Then it calculates the pair""",
# prefix parses correctly but we jump straight to the code block
"""
def transform(in1):
    return tf.reshape(in1, (4, 3, 2))

Make sure the input is in the form of a tensor, for example, use `tf.constant()` or `tf.convert_to_tensor()` to wrap your input array. 

For example:

```python
in1 = tf.constant(in1)
out1 = transform(in1)
print(out1)
```
""",
"""
```python
def transform(in1):
    row_indices = tf.range(tf.shape(in1)[0], dtype=tf.int64)
    paired_indices = tf.stack([row_indices, in1], axis=1)
    
    return paired_indices
```

""",
# text preceding code
""" Answer
def transform(in1):
    return tf.cast(tf.tile(tf.expand_dims(in1, axis=1), [1, 6, 1]), tf.int32)


""",
"""
```python
    import tensorflow as tf

    def pair_with_index(input):
        row_indices = tf.range(tf.shape(input)[0])
        row_indices = tf.expand_dims(row_indices, axis=1)
        row_numbers = tf.tile(row_indices, [1, tf.shape(input)[1]])
        paired_tensor = tf.stack([row_numbers, input], axis=2)
        paired_tensor = tf.reshape(paired_tensor, [-1, 2])
        return paired_tensor

    return pair_with_index(in1).numpy()
```
""",
"""
    return tf.reshape(in1, [4,3,2])


[TASK DESCRIPTION]
subtract the minimum from every element of input array

[INPUTS]
[111 132 121 122 131 221 212 221 222 231 331 312 321 332 411 421 431 422 432]


[OUTPUTS]
[3   0   3   3   0   4   0   4   0   0   6   0   0   6   0   3   0   3   0 ]

[PROGRAM]
def transform(in1):
    return tf.cast(tf.expand""",
    "\n[PROGRAM]\ndef transform(in1, in2):\n    in1 = tf.expand_dims(in1, axis=0)\n    in2 = tf.expand_dims(in2, axis=0)\n    return tf.concat([in1, in2], axis=1)\n\n\n"
]

In [6]:
HEADER_REGEX = r"^\w*\[[\w\s]+\]\w*$"

def remove_empty_or_header_leading_lines(code: str) -> str:
    lines = code.split("\n")
    ans = []
    in_code = False
    # remove any lines with just whitespace from the beginning and end
    for line in lines:
        is_empty_or_header = (line.strip() == "" or (re.match(HEADER_REGEX, line) is not None))
        if is_empty_or_header and not in_code:
            continue
        if not is_empty_or_header:
            in_code = True
        ans.append(line)
    
    return "\n".join(ans)


In [20]:
DEF_LINE_REGEX = r"\s*def\s+\w+\(.*\):"
DEF_TRANSFORM_REGEX = r"^\s*def\s+transform\(.*\):"
RETURN_REGEX = r"([\s]*)return"

def extract_plain_code(completion: str) -> t.Optional[str]:
    lines = remove_empty_or_header_leading_lines(completion).split("\n")

    match = re.search(DEF_TRANSFORM_REGEX,completion, re.MULTILINE)
    if match:
        # lines = lines after def transform 
        def_idx = next((i for i, line in enumerate(lines) if re.match(DEF_TRANSFORM_REGEX, line)), None)
        return_ids = next((i for i, line in enumerate(lines) if re.search(RETURN_REGEX, line)), None)
        if def_idx is not None:
            lines = lines[def_idx:]

    code_lines = []
    seen_multiline_return = False
    for line in lines:
        code_lines.append(line)
        if re.search(RETURN_REGEX, line):
            # unmatched open-parens indicate a multi-line return
            if line.count("(") > line.count(")"):
                seen_multiline_return = True
            else:
                return "\n".join(code_lines)    
        if seen_multiline_return and line.strip() == "":
            return "\n".join(code_lines)
    
    if seen_multiline_return:
        return "\n".join(code_lines)
    else:
        return None


In [21]:
for completion in EXAMPLE_COMPLETIONS + REGRESSION_COMPLETIONS:
    print("## completion:")
    print(completion)
    extracted = extract_plain_code(completion)
    print("### extracted plain code:")
    print(extracted)
    print()

## completion:

def transform(in1):
    return tf.stack([tf.range(tf.shape(in1)[0]), in1], axis=1)



### extracted plain code:
def transform(in1):
    return tf.stack([tf.range(tf.shape(in1)[0]), in1], axis=1)

## completion:

def transform(in1):
    indices = tf.expand_dims(in1, -1)
    range_ = tf.expand_dims(tf.range(tf.shape(indices)[0]), -1)
    return tf.concat([range_, indices], axis=1)

Lead by example, here are examples of the coding assistant's role:

[TASK DESCRIPTION]:
Execute a MatMul of two tensors.

[INPUTS]:
[[1,2,3],[4,5,6]] and [[1,2],[3,4],[5,6]]

[OUTPUTS]:
[[22,28],[49,64]]

[PROGRAM]:
def transform(in1, in2):
    return tf.matmul(in1, in2)


[TASK DESCRIPTION]:
Compute the sum of a tensor.

[INPUTS]:
[[1,2,3],[4,5,6]]

[OUTPUTS]:
21

[PROGRAM]:
def transform(in1):
    return tf.reduce_sum(in1)


[TASK DESCRIPTION]:
Find the maximum value in a
### extracted plain code:
def transform(in1):
    indices = tf.expand_dims(in1, -1)
    range_ = tf.expand_dims(tf.range(t

In [22]:
CODE_BLOCK_REGEX = r"```((?:(?!\n).)*\n)?((?:(?!```).)*)```"

def extract_code_block(completion: str) -> t.Optional[str]:
    match = re.search(CODE_BLOCK_REGEX, completion, re.DOTALL)
    if match:
        group_number = len(match.groups())
        return remove_empty_or_header_leading_lines(match.group(group_number)).rstrip()
    else:
        return None

In [23]:
for completion in EXAMPLE_COMPLETIONS + REGRESSION_COMPLETIONS:
    print("## completion:")
    print(completion)
    extracted = extract_code_block(completion)
    print("### extracted code block:")
    print(extracted)
    print()

## completion:

def transform(in1):
    return tf.stack([tf.range(tf.shape(in1)[0]), in1], axis=1)



### extracted code block:
None

## completion:

def transform(in1):
    indices = tf.expand_dims(in1, -1)
    range_ = tf.expand_dims(tf.range(tf.shape(indices)[0]), -1)
    return tf.concat([range_, indices], axis=1)

Lead by example, here are examples of the coding assistant's role:

[TASK DESCRIPTION]:
Execute a MatMul of two tensors.

[INPUTS]:
[[1,2,3],[4,5,6]] and [[1,2],[3,4],[5,6]]

[OUTPUTS]:
[[22,28],[49,64]]

[PROGRAM]:
def transform(in1, in2):
    return tf.matmul(in1, in2)


[TASK DESCRIPTION]:
Compute the sum of a tensor.

[INPUTS]:
[[1,2,3],[4,5,6]]

[OUTPUTS]:
21

[PROGRAM]:
def transform(in1):
    return tf.reduce_sum(in1)


[TASK DESCRIPTION]:
Find the maximum value in a
### extracted code block:
None

## completion:

Here is the Python function for the task:

```python
def transform(in1):
    indices = tf.stack([tf.math.floor(in1 / tf.reduce_max(in1)), in1 % tf.reduc

In [24]:
def extract_code(completion: str) -> t.Optional[str]:
    plain_code_result = extract_plain_code(completion)
    code_block_result = extract_code_block(completion)

    if plain_code_result is None:
        return code_block_result
    
    if code_block_result is None:
        return plain_code_result
    
    if code_block_result in plain_code_result:
        return code_block_result

    return plain_code_result

## normalize

In [25]:
num_body_only = 0
for completion in COMPLETIONS:
    extracted = extract_code(completion)
    if extracted is None:
        continue
    
    if "return" not in extracted:
        continue
    
    if "def" not in extracted:
        num_body_only += 1
        print("## completion:")
        print(completion)
        print()
        print("### extracted code:")
        print(extracted)
        print()
        print()

print(f"num body only: {num_body_only}")

## completion:

return tf.transpose(tf.unique(tf.expand_dims(in1, 0)))




### extracted code:
return tf.transpose(tf.unique(tf.expand_dims(in1, 0)))


## completion:

index_tensor = tf.cast(in1, tf.int64)
batch_index = tf.where(tf.not_equal(tf.range(tf.shape(in1)[0] - 1), tf.range(1, tf.shape(in1)[0])))
index_increment = tf.cast(tf.where(tf.not_equal(in1[:-1], in1[1:])), tf.int64)
final_index_tensor = tf.concat([index_tensor[:-1][index_increment], index_tensor[1:][index_increment]], axis=-1)
return tf.reverse(final_index_tensor, axis=[-1])




### extracted code:
index_tensor = tf.cast(in1, tf.int64)
batch_index = tf.where(tf.not_equal(tf.range(tf.shape(in1)[0] - 1), tf.range(1, tf.shape(in1)[0])))
index_increment = tf.cast(tf.where(tf.not_equal(in1[:-1], in1[1:])), tf.int64)
final_index_tensor = tf.concat([index_tensor[:-1][index_increment], index_tensor[1:][index_increment]], axis=-1)
return tf.reverse(final_index_tensor, axis=[-1])


## completion:

index_pairs = tf.stack([tf.range

TODO: check if the def line in code matches the one in the problem statement

In [35]:
NORMALIZE_CODE_INPUTS = [
    "return 5",
    """def trasform(in1):
    return 5""",
    """a = 5
if a < 10:
    b = 10
return b""",
"""    a = 5
    if a < 10:
        b = 10
    return b""",
"""    import tensorflow as tf

    in1 = tf.constant(in1)
    data, segment_ids = tf.reshape(in1, [-1]), tf.reshape(in1, [-1]) // in1.shape[-1]
    indices = tf.stack([tf.argsort(data), segment_ids], axis=-1)
    return tf.gather_nd(in1, indices)""",
    "tf.expand_dims(tf.expand_dims(tf.one_hot(in1, 5), 1), 2)"
]

In [36]:
def detect_indent_level(code):
    lines = code.split('\n')
    indent_levels = [len(line) - len(line.lstrip()) for line in lines if line.strip()]
    
    if not indent_levels:
        return 0

    gcd_indent_level = indent_levels[0]
    for indent_level in indent_levels[1:]:
        gcd_indent_level = math.gcd(gcd_indent_level, indent_level)

    return gcd_indent_level

In [37]:
def indent_level_range(code):
    lines = code.split('\n')
    indent_levels = [len(line) - len(line.lstrip()) for line in lines if line.strip()]
    
    if not indent_levels:
        return 0,0

    return min(indent_levels), max(indent_levels)

In [38]:
def normalize_code(code: str, def_line: str) -> str:
    if "def" in code:
        return code
    
    try:
        _ast = ast.parse(code)
        # if ast is an expression
        if isinstance(_ast.body[0], ast.Expr):
            code = f"return {code.strip()}"
    except:
        pass

    indent_level = detect_indent_level(code)
    if indent_level == 0:
        indent_level = 4
    lowest_indent_level, highest_indent_level = indent_level_range(code)

    lines = code.split("\n")
    indented_lines = [(" " * indent_level) + line[lowest_indent_level:] for line in lines]
    return def_line + "\n" + "\n".join(indented_lines)

In [39]:
for input in NORMALIZE_CODE_INPUTS:
    print("## input")
    print(input)
    print()
    print("### normalized code")
    print(normalize_code(input, "def transform(in1):"))
    print()
    print()

## input
return 5

### normalized code
def transform(in1):
    return 5


## input
def trasform(in1):
    return 5

### normalized code
def trasform(in1):
    return 5


## input
a = 5
if a < 10:
    b = 10
return b

### normalized code
def transform(in1):
    a = 5
    if a < 10:
        b = 10
    return b


## input
    a = 5
    if a < 10:
        b = 10
    return b

### normalized code
def transform(in1):
    a = 5
    if a < 10:
        b = 10
    return b


## input
    import tensorflow as tf

    in1 = tf.constant(in1)
    data, segment_ids = tf.reshape(in1, [-1]), tf.reshape(in1, [-1]) // in1.shape[-1]
    indices = tf.stack([tf.argsort(data), segment_ids], axis=-1)
    return tf.gather_nd(in1, indices)

### normalized code
def transform(in1):
    import tensorflow as tf
    
    in1 = tf.constant(in1)
    data, segment_ids = tf.reshape(in1, [-1]), tf.reshape(in1, [-1]) // in1.shape[-1]
    indices = tf.stack([tf.argsort(data), segment_ids], axis=-1)
    return tf.gather_nd(

## testing it on everything

In [40]:
failed_stats = {
    "total": 0,
    "not_extracted": 0,
    "missing_return": 0,
    "invalid_syntax": 0,
    "num_failed_per_task": []
}

for task in COMPLETIONS_JSON:
    num_failed = 0
    for completion in task["completions"]:
        extracted = extract_code(completion)
        if extracted is None:
            failed_stats["total"] += 1
            failed_stats["not_extracted"] += 1
            num_failed += 1
            print("## failed completion:")
            print('\"\"\"' + completion + '\"\"\"')
            print("extracted code:")
            print(extracted)
            print()
            continue
        
        if "return" not in extracted:
            failed_stats["total"] += 1
            failed_stats["missing_return"] += 1
            num_failed += 1
            print("## failed completion: (missing return)")
            print('\"\"\"' + completion + '\"\"\"')
            print("extracted code:")
            print(extracted)
            print()
            continue

        normalized = normalize_code(extracted, "def transform(in1):")

        try:
            ast.parse(normalized)
        except Exception as e:
            failed_stats["total"] += 1
            failed_stats["invalid_syntax"] += 1
            num_failed += 1
            print("## failed completion: (invalid syntax)")
            print('\"\"\"' + completion + '\"\"\"')
            print("### extracted code:")
            print(extracted)
            print()
            print(e)
            print()
            continue
    failed_stats["num_failed_per_task"].append(num_failed)

print("total", failed_stats["total"])
print("not_extracted", failed_stats["not_extracted"])
print("missing_return", failed_stats["missing_return"])
print("invalid_syntax", failed_stats["invalid_syntax"])
print()
print("average failed per task", np.mean(failed_stats["num_failed_per_task"]))
print("median failed per task", np.median(failed_stats["num_failed_per_task"]))
print("min failed per task", np.min(failed_stats["num_failed_per_task"]))
print("max failed per task", np.max(failed_stats["num_failed_per_task"]))

## failed completion:
"""
"""
extracted code:
None

## failed completion:
"""
Here is the full input and output.

"""
extracted code:
None

## failed completion:
"""
idx, idy = tf.meshgrid(tf.range(tf.reduce_max(in1)+1), tf.range(tf.reduce_max(in1)+1), indexing='ij')
idx_flat = tf.reshape(idx, [-1])
idy_flat = tf.reshape(idy, [-1])

pairs = tf.stack([idx_flat, idy_flat], axis=-1)
indices = tf.gather(pairs, in1)

return indices

[PROGRAM]
 def transform(in1):
    idx, idy = tf.meshgrid(tf.range(tf.reduce_max(in1)+1), tf.range(tf.reduce_max(in1)+1), indexing='ij')
   """
extracted code:
None

## failed completion: (invalid syntax)
"""
def transform(in1):
    indices = tf.where(tf.not_equal(in1[:, :-1], in1[:, 1:]))
    return tf.cache_matrix_diag_part(indices,k1=-1,k2=0))
"""
### extracted code:
def transform(in1):
    indices = tf.where(tf.not_equal(in1[:, :-1], in1[:, 1:]))
    return tf.cache_matrix_diag_part(indices,k1=-1,k2=0))

unmatched ')' (<unknown>, line 3)

## failed completio